@startuml
Project starts 2020-12-09
2020-12-24 to 2021-01-03 are closed
2020-12-19 to 2021-01-10 are named [Weihnachtsferien] and are colored in lightgreen
2020-12-24 to 2020-12-26 are colored in green
2020-12-31 to 2021-01-01 are colored in OrangeRed
[Meeting 4] happens at 2020-12-16
[Meeting 5] happens at 2021-01-13 and displays on same row as [Meeting 4]
[Meeting 6] happens at 2021-01-20 and displays on same row as [Meeting 5]
[Meeting 7] happens at 2021-01-27 and displays on same row as [Meeting 6]
[Meeting 8] happens at 2021-02-03 and displays on same row as [Meeting 7]
[Project presentation] happens at 2021-02-10 and is colored in red
[Meeting 4] displays on same row as [Project presentation]

-- Backend --
[Backend Aufgaben besprechen] as [BA] happens at 2020-12-14

then [Game manager skeleton] lasts 10 days and is 0% complete
then [full Game manager] lasts 10 days and is 0% complete
[BA] -> [Matchmaker lambda script]
[Matchmaker lambda script] lasts 5 days and is 0% complete
[Game manager skeleton] -> [Deploy server fleet Alpha]
[Matchmaker lambda script] -> [Deploy server fleet Alpha]
[Deploy server fleet Alpha] lasts 3 days and is 0% complete
[BA] -> [initial M3 board]
[initial M3 board] lasts 10 days and is 0% complete
then [Game logic M3] lasts 18 days and is 0% complete
[BA] -> [initial SSPS board]
[initial SSPS board] lasts 9 days and is 0% complete
then [Game logic SSPS] lasts 21 days and is 0% complete
[initial M3 board] -> [Deploy server fleet Beta]
[initial SSPS board] -> [Deploy server fleet Beta]
[full Game manager] -> [Deploy server fleet Beta]
[Deploy server fleet Alpha] -> [Deploy server fleet Beta]
[Deploy server fleet Beta] lasts 2 days and is 0% complete
[BA] -> [Game logic test script]
[Game logic test script] lasts 7 days and is 0% complete
then [Game logic test cases] lasts 14 days and is 0% complete
[BA] -> [DynamoDB instance]
[DynamoDB instance] starts 2020-12-15 and lasts 7 days and is 0% complete

-- Frontend SSPS --

[SSPS implementation kickoff] as [SSPS] happens at 2020-12-14


then [Tile: static] lasts 7 days and is 0% complete
then [Tile: Character assignment] lasts 5 days and is 0% complete
[Tile: Highlighting] lasts 5 days and is 0% complete
[Tile: static] -> [Tile: Highlighting]
[Board: index tiles] lasts 5 days and is 0% complete
[Tile: static] -> [Board: index tiles]
then [Board: Move validation] lasts 5 days and is 0% complete
[UI elements] starts 2021-01-11 and lasts 10 days and is 0% complete
[UI: Highlighting] lasts 6 days and is 0% complete
[UI: turn timer] lasts 6 days and is 0% complete
[UI: turn indicator] lasts 6 days and is 0% complete
[UI elements] -> [UI: Highlighting]
[UI elements] -> [UI: turn timer]
[UI elements] -> [UI: turn indicator]

[UI: Pre-Game elements] starts 2021-01-11 and lasts 5 days and is 0% complete

[SSPS] -> [Character: graphical representation]
[SSPS] -> [Character: internal representation]
[Character: graphical representation] lasts 4 days and is 0% complete
[Character: internal representation] lasts 2 days and is 0% complete
[Board: index tiles] -> [Character: position]
[Board: index tiles] -> [Character: move]

[SSPS] -> [Spawner: initial setup]
[Spawner: initial setup] lasts 4 days and is 0% complete
then [Spawner: reset] lasts 4 days and is 0% complete

[Spawner: initial setup] -> [PieceManager: index]
[PieceManager: index] lasts 4 days and is 0% complete
then [PieceManager: move] lasts 4 days and is 0% complete
then [PieceManager: combat] lasts 4 days and is 0% complete
then [PieceManager: remove] lasts 4 days and is 0% complete

[PieceManager: move] -> [Character: move]
[Character: position] lasts 4 days and is 0% complete
[Character: move] lasts 4 days and is 0% complete
[Character: internal representation] -> [Character: specialization]
[Character: graphical representation] -> [Character: specialization]
[Character: specialization] lasts 4 days and is 0% complete
[PieceManager: index] -> [PieceManager: weapon distribution]
[PieceManager: weapon distribution] lasts 4 days and is 0% complete
[Turn: Countdown] -> [Turn: Networking integration]
[PieceManager: Networking integration] starts at [Deploy server fleet Beta]'s end and lasts 7 days

[AudioManager] starts 2021-01-11 and lasts 4 days and is 0% complete

[SSPS] -> [GameManager]
[GameManager] lasts 4 days and is 0% complete

[SSPS] -> [Input: touch handling]
[Input: touch handling] lasts 5 days and is 0% complete
then [Input: clickable object] lasts 5 days and is 0% complete

[SSPS] -> [Networking: SDK, setup]

[Networking: SDK, setup] lasts 5 days and is 0% complete
[Networking: send/receive commands] starts at [Deploy server fleet Alpha]'s end and is 0% complete and lasts 7 days
[Networking: SDK, setup] -> [Networking: validation]
[Networking: validation] -> [Networking: error handling]
[Networking: validation] starts at [Deploy server fleet Alpha]'s end and is 0% complete and lasts 7 days
[Networking: error handling] starts at [Networking: validation]'s end and lasts 7 days

[Networking: send/receive commands] -> [Turn: Networking integration]


[SSPS] -> [Turn: skeleton, local parts]
[Turn: skeleton, local parts] lasts 7 days and is 0% complete

[Turn: skeleton, local parts] -> [Turn: permission handling]
[Turn: skeleton, local parts] -> [Turn: UI integration]
[Turn: skeleton, local parts] -> [Turn: Countdown]
[Game manager skeleton] -> [Turn: permission handling]
[Game manager skeleton] -> [Turn: UI integration]
[Game manager skeleton] -> [Turn: Countdown]
[Turn: Networking integration] lasts 5 days and starts at [Deploy server fleet Beta]'s end
[Turn: permission handling] lasts 5 days and is 0% complete
[Turn: UI integration] lasts 5 days and is 0% complete
[Turn: Countdown] lasts 5 days and is 0% complete

[Meeting 7] -> [Dedicated Integration buffer]
[Dedicated Integration buffer] lasts 7 days and is 0% complete
then [Quality: and testing] lasts 4 days and is 0% complete
[Dedicated Integration buffer] -> [Bugfixes]
[Bugfixes] lasts 4 days and is 0% complete

[Meeting 7] -> [Presentation preparation]
[Presentation preparation] lasts 13 days and is 0% completed

[Integrate various missing Assets] lasts 7 days and is 0% complete
[Integrate SSPS characters] lasts 3 days and is 0% complete
[Integrate SSPS movement anims] lasts 3 days and is 0% complete
[Integrate SSPS UI] lasts 3 days and is 0% complete

-- Frontend M3 --

-- Design --
[Design Milestone] as [DM] happens at 2020-12-09

then [Game characters SSPS] lasts 10 days and is 0% complete
[Game characters SSPS] is colored in #fca903
[Game characters SSPS] -[#fca903]> [Character animations SSPS]
[Character animations SSPS] is colored in #fca903
[Character animations SSPS] lasts 7 days and is 0% complete
[Game characters SSPS] -[#fca903]> [Movement animation SSPS]
[Movement animation SSPS] is colored in #fca903
[Movement animation SSPS] starts at 2021-01-14
[Movement animation SSPS] lasts 5 days and is 0% complete
[Game characters SSPS] -[#fca903]> ["Dying" animation SSPS]
["Dying" animation SSPS] is colored in #fca903
["Dying" animation SSPS] starts at 2021-01-19
["Dying" animation SSPS] lasts 5 days and is 0% complete
[Game characters SSPS] -> [Win animation SSPS]
[Game characters SSPS] -[#0356fc]> [Win animation SSPS]
[Win animation SSPS] starts at 2021-01-27
[Win animation SSPS] is colored in #0356fc
[Win animation SSPS] lasts 5 days and is 0% complete

[Game characters SSPS] -[#0356fc]> [Trap SSPS]
[Trap SSPS] is colored in #0356fc
[Trap SSPS] starts at 2021-01-17
[Trap SSPS] lasts 5 days and is 0% complete
[Trap SSPS] -[#0356fc]> [Trap animation SSPS]
[Trap animation SSPS] is colored in #0356fc
[Trap animation SSPS] lasts 5 days and is 0% complete
[Game characters SSPS] -[#0356fc]> [King SSPS]
[King SSPS] starts at 2021-01-04
[King SSPS] is colored in #0356fc
[King SSPS] lasts 5 days and is 0% complete

[Game characters SSPS] -> [Fighting animations SSPS]
[Weapons SSPS] -> [Fighting animations SSPS]
[Fighting animations SSPS] starts at 2020-12-25
[Fighting animations SSPS] lasts 14 days and is 0% complete

[Weapons SSPS] starts at 2020-12-14
[Weapons SSPS] is colored in #fca903
[Weapons SSPS] lasts 10 days and is 0% complete

[Weapons SSPS] -[#fca903]> [Weapon selection window SSPS]
[Weapon selection window SSPS] is colored in #fca903
[Weapon selection window SSPS] starts at 2021-01-29
[Weapon selection window SSPS] lasts 3 days and is 0% complete

[Game interface SSPS] starts at 2021-01-18
[Game interface SSPS] is colored in #fca903
[Game interface SSPS] lasts 10 days and is 0% complete

[Initial Screen SSPS] starts at 2021-01-15
[Initial Screen SSPS] is colored in #fca903
[Initial Screen SSPS] lasts 5 days and is 0% complete
[Initial Screen SSPS] -[#fca903]> [Starting animation SSPS]
[Starting animation SSPS] is colored in #fca903
[Starting animation SSPS] lasts 5 days and is 0% complete

[Texts and buttons SSPS] starts at 2021-01-29
[Texts and buttons SSPS] is colored in #fca903
[Texts and buttons SSPS] lasts 5 days and is 0% complete

[Referee SSPS] starts at 2021-01-17
[Referee SSPS] is colored in #0356fc
[Referee SSPS] lasts 10 days and is 0% complete
[Referee SSPS] -[#0356fc]> [Turn display SSPS]
[Turn display SSPS] lasts 3 days and is 0% complete
[Turn display SSPS] is colored in #0356fc

[Final Screen SSPS] starts at 2021-01-28
[Final Screen SSPS] is colored in #0356fc
[Final Screen SSPS] lasts 5 days and is 0% complete

[Arrows SSPS] starts at 2021-01-31
[Arrows SSPS] is colored in #0356fc
[Arrows SSPS] lasts 3 days and is 0% complete

/'M3'/
[DM] -[#ff00ee]> [Game characters M3]
[Game characters M3] is colored in #ff00ee

[Game characters M3] lasts 10 days and is 0% complete
[Game characters M3] -[#ff00ee]> [Character animations M3]
[Character animations M3] is colored in #ff00ee
[Character animations M3] lasts 10 days and is 0% complete
[Game characters M3] -[#ff00ee]> [Win animation]
[Win animation] starts at 2021-01-20
[Win animation] is colored in #ff00ee
[Win animation] lasts 7 days and is 0% complete

[Game characters M3] -[#ff00ee]> [Score animation M3]
[Score animation M3] starts at 2021-01-06
[Score animation M3] is colored in #ff00ee
[Score animation M3] lasts 14 days and is 0% complete

[Game characters M3] -> [Tile insertion M3]
[Game tiles M3] -> [Tile insertion M3]
[Tile insertion M3] starts at 2021-01-11
[Tile insertion M3] lasts 14 days and is 0% complete

[DM] -[#0356fc]> [Game tiles M3]
[Game tiles M3] is colored in #0356fc
[Game tiles M3] lasts 10 days and is 0% complete
[Game tiles M3] -[#ff00ee]> [Score explanation M3]
[Score explanation M3] starts at 2021-01-30
[Score explanation M3] is colored in #ff00ee
[Score explanation M3] lasts 3 days and is 0% complete
[Game tiles M3] -[#0356fc]> [Game tile animations M3]
[Game tile animations M3] is colored in #0356fc
[Game tile animations M3] lasts 14 days and is 0% complete

[DM] -[#0356fc]> [Timer SSPS & M3]
[Timer SSPS & M3] is colored in #0356fc
[Timer SSPS & M3] lasts 7 days and is 0% complete

[Texts and buttons M3] starts at 2021-01-29
[Texts and buttons M3] is colored in #ff00ee
[Texts and buttons M3] lasts 5 days and is 0% complete

[Game interface M3] starts at 2020-12-13
[Game interface M3] is colored in #ff00ee
[Game interface M3] lasts 10 days and is 0% complete

[Final Screen M3] starts at 2021-01-06
[Final Screen M3] is colored in #ff00ee
[Final Screen M3] lasts 7 days and is 0% complete

[Turn display M3] starts at 2021-01-15
[Turn display M3] is colored in #ff00ee
[Turn display M3] lasts 5 days and is 0% complete

[Scoreboards M3] starts at 2021-01-27
[Scoreboards M3] is colored in #ff00ee
[Scoreboards M3] lasts 5 days and is 0% complete

[Initial Screen M3] starts at 2021-01-15
[Initial Screen M3] is colored in #ff00ee
[Initial Screen M3] lasts 7 days and is 0% complete
[Initial Screen M3] -[#ff00ee]> [Starting animation M3]
[Starting animation M3] is colored in #ff00ee
[Starting animation M3] lasts 5 days and is 0% complete

/'Area for dependencies that need to be defined at EOF'/

[Arrows SSPS] -> [Integrate various missing Assets]
[Character animations SSPS] -> [Integrate SSPS characters]
[Movement animation SSPS] -> [Integrate SSPS movement anims]
[Game interface SSPS] -> [Integrate SSPS UI]
@enduml